### ISSUE TITLE
Text Field on initial menu is editable by user

### ISSUE THREAD

**Issue by JeremyWinkler** [khallman97/2311-project#2]
Severity - Trivial
Version - vM
Component - Initial Menu
Platform - PC
OS - Windows (I believe it is the same for other OS)
Java Version - 8
Description: The text field on the initial menu is editable by the user, yet does nothing.

Steps: Open the program, Click on the text field. 

Actual Results: User is able to edit this text.

Expected Result: User shouldn't be able to edit this field as it implies that the user should type 
something in here.

Build Date: 3/5/2018

**Comment by gnuch** [comment]
Authoring.java

Line 102:
output.setEditable(false);
