### ISSUE TITLE
Application too small for itself on Linux

### ISSUE THREAD

**Issue by tynt7** [khallman97/2311-project#3]
Severity: Severe
Version: vM
Component: AuthoringApp
Platform: Laptop
OS: Linux
Java Version: 8
Description: Window is too small to see all components, rendering user unable to interact and create scenarios.

Steps: Launch program, navigate to AuthoringApp.
 
![authoringapplinux](https://user-images.githubusercontent.com/35306360/37072072-a5af5bd4-218d-11e8-816f-0c866f74bfe0.png)
Actual Results: A non-resizeable window with components in it.

Expected Result:  A window of a size fitting it's requirements.

Build Date: 3/6/2018

**Comment by khallman97** [comment]
Fixed sizing for the window
